#######################################################################################
# Book settings
title                       : mitigation project
author                      : Michael Barnett, William Brock, Lars Peter Hansen, and Hong Zhang
logo                        : mfr.png
only_build_toc_files        : true # Disable building files that aren’t in the Table of Contents

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : 'auto'
  exclude_patterns          : ['notebook.md']
  exclude_tags:
    - 'no-execute'
  timeout: -1
#######################################################################################
# LaTeX-specific settings
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname              : book.tex

bibtex_bibfiles:
  - climate.bib

#######################################################################################
# HTML-specific settings
html:
  favicon: mfr.png
  home_page_in_navbar       : false
  use_edit_page_button      : true
  use_repository_button     : true
  use_issues_button         : true
  announcement              : "" # A banner announcement at the top of the site.

#######################################################################################
# Launch button settings
repository:
  url                       : https://github.com/zhaoyang8/mitigation_book
  path_to_book              : docs
  branch                    : live

launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  colab_url                 : https://colab.research.google.com # The URL of Google Colab (https://colab.research.google.com)
  thebe                     : true

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

sphinx:
  extra_extensions:
    - sphinx_inline_tabs
    - sphinx_external_toc
    - sphinxcontrib.bibtex
    - sphinx_proof
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    bibtex_reference_style: author_year
    bibtex_default_style: plain